[package]
name = "easycron"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
cron = "0.15.0"
derive_builder = "0.20.2"
nanoid = "0.4.0"
tokio = { version = "1.43.0", features = ["full"] }
